### ISSUE TITLE
training new tracking model

### ISSUE THREAD

**Issue by Yakirbe** [nwojke/deep_sort#1]
hi,
any upcoming training - testing new tracking apps, trained from scratch examples(non pedestrian) predicted soon?

**Comment by nwojke** [comment]
For now we only target pedestrian tracking applications, since this is what most tracking benchmarks evaluate on. However, if you have a large (non-pedestrian) dataset for your application scenario, integration into the framework should be possible with few adaptions (mostly generating new detections and changing the Kalman filter parametrization).
