### ISSUE TITLE
Unsuccessful TensorSliceReader constructor: Failed to find any matching files for ./resources/networks/mars-small128.ckpt

### ISSUE THREAD

**Issue by PetreanuAndi** [nwojke/deep_sort#23]
The paths are correct and directory structure is as mentioned. 
Tracking demo works fine, problem arises at feature generation, running the command mentioned in your README. TF version is 1.3, mars-small128.ckpt is there. 

Any ideas? Thank you!

**Comment by nwojke** [comment]
I might have seen that before. Can you try passing in an absolute path?

**Comment by PetreanuAndi** [comment]
Hello. Sorry, you can close this. It was a simple mistake. 
For anyone else interested, you need to pass the name to ckpt in full, like mars-small128.ckpt-68577. Tracker works! Amazing stuff.

I'm trying to keep track of some real-time detections. 
Any tips on how to improve using the max_cosine_distance, a different distance metric all together, or some special aspect-ratio / sizing for the rescale of image crops? My objects are quite small, i get a lot of re-identification.

**Comment by nwojke** [comment]
Glad to hear your problem was easy to resolve. I close this since the original question has been answered.

About your second question: I might be able to provide some code to visually inspect how to set the cosine distance, but that would require a separate training set where you can tune parameters. Do you have that?
