### ISSUE TITLE
Why is each parameter in the Kalman filter covariance matrix initialized with "measure [3]" which is the height of the input bbox?

### ISSUE THREAD

**Issue by Ancho5515** [nwojke/deep_sort#253]
initiate function in class KalmanFilter :
`
std = [
            2 * self._std_weight_position * measurement[3],  
            2 * self._std_weight_position * measurement[3],  
            1e-2,  
            2 * self._std_weight_position * measurement[3],  
            10 * self._std_weight_velocity * measurement[3],  
            10 * self._std_weight_velocity * measurement[3],  
            1e-5,  
            10 * self._std_weight_velocity * measurement[3]]  
        covariance = np.diag(np.square(std))  
        return mean, covariance`

you can also find it in predict and project function.

**Comment by studentbrad** [comment]
There is no depth information.  The covariance is heavily dependent on the depth of the target in the camera.  So, the height of the bounding box is a good alternative.  Because a smaller height means a a higher depth; whereas a larger height means lower depth.  Depth matters because it tells us how far a target could potentially move in a single frame in the image plane.

**Comment by Ancho5515** [comment]
@studentbrad Thanks for your explanation, that's really helps
