### ISSUE TITLE
How to adjust the cost contributed by appearance similarity versus iou?

### ISSUE THREAD

**Issue by JRCondeNast** [nwojke/deep_sort#27]

**Comment by nwojke** [comment]
At the moment IOU is a secondary assocation cost that is applied in a second association stage after appearance based matching. If you want to weigh in IOU into the matching cascade you would have to fiddle around with the [gated cost computation](https://github.com/nwojke/deep_sort/blob/master/deep_sort/tracker.py#L95).

**Comment by goldentimecoolk** [comment]
Hi @nwojke , I have a question about this point. According to the list 1 in your origon paper DeepSort, you compute cost matrix C based on both motion and appearance information, which are weighed by lambda. And cascade matching is iterated by age of tracks. But from the code, appearance and motion information is used in series instead of parallel. Is this the representation of 'cascade' for cascade matching? Could explain the reason of this difference between code and paper? Thank you.
