### ISSUE TITLE
Is there any reference for computing covariance of motion and observation variables?

### ISSUE THREAD

**Issue by animebing** [nwojke/deep_sort#51]
Hi, nwojke, although it is said that  it is a bit hacky to set the motion and observation uncertainty, it seems that there is a pattern in `kalman_filter.py` when you initiate `covariance` in `initiate` phase, compute `motion_cov` in `predict` phase and `innovation_cov` in `project` phase, can you show me some reference or suggestion to set these variables? Thank you.

**Comment by nwojke** [comment]
The parametrization was roughly inspired by the code of [MHT-DAM](http://rehg.org/mht/). The general idea was to set motion and observation uncertainty based on the size of the object and then reduce the parametrization to few parameters (std_weight_position and std_weight_velocity). It is hacky, because in the prediction [here](https://github.com/nwojke/deep_sort/blob/master/deep_sort/kalman_filter.py#L107) the motion uncertainty depends on the mean of the estimate which is a violation of Kalman filtering assumptions. The same holds for the observation uncertainty.

**Comment by animebing** [comment]
In the Kalman filter assumptions, the covariance should be pre-defined and fixed instead of dynamic adjusting?

**Comment by nwojke** [comment]
It may change at every time step but should be independent of state.

**Comment by animebing** [comment]
Thanks for pointing out this, I got it.
