### ISSUE TITLE
Different bounding boxes

### ISSUE THREAD

**Issue by tomhayat** [nwojke/deep_sort#73]
Hi,
Thank you for your amazing work.
I don't understand why the bounding boxes coordinates in my detection files are different before and after deepsort algorithm.
How can I match the feature vectors from ReIdentification CNN to the detection file created after deepsort.
Thanks in advance
Tom

**Comment by firesharker** [comment]
The bounding boxes coordinates are different, because as you can see [here](https://github.com/nwojke/deep_sort/blob/d339f75b22c5b2ab061c9cc1ea546c448cdfb9f6/deep_sort_app.py#L197) the stored values are computed from the Kalman filter's state. If you want to get the exact bounding box coordinates, you need to store the associated detections during matching.

**Comment by tomhayat** [comment]
Thanks !!!

**Comment by antocapp** [comment]
Hello, how can I get exact bounding box coordinates?

**Comment by jane212** [comment]
> The bounding boxes coordinates are different, because as you can see [here](https://github.com/nwojke/deep_sort/blob/d339f75b22c5b2ab061c9cc1ea546c448cdfb9f6/deep_sort_app.py#L197) the stored values are computed from the Kalman filter's state. If you want to get the exact bounding box coordinates, you need to store the associated detections during matching.

Hi, do you know how to store the detection bbox during matching? or just store the detection_idx? Thank you!

**Comment by jane212** [comment]
@firesharker Hi, do you know how to store the detection bbox during matching? or just store the detection_idx? Thank you!
