### ISSUE TITLE
Can i store track state in file for future use?

### ISSUE THREAD

**Issue by K0307** [nwojke/deep_sort#8]
I have multiple videos and there corresponding detection files . So i want to store track state of first video in file and use this track state detection file for next video.

**Comment by harshmunshi** [comment]
Combine all the videos to one big video file using ffmpeg. Should work.

**Comment by nwojke** [comment]
Sorry for the late reply. It looks like `nn_matching.NearestNeighborDistanceMetric` is not pickable at the moment due to using a local function as class attribute. This is quite easy to fix by moving `nn_euclidean_distance` and `nn_cosine_distance` in `deep_sort.nn_matching` to module level. Then, you can pickle the tracker and restore its state:

```
from deep_sort.tracker import Tracker
from deep_sort import nn_matching

# Create tracker.
metric = nn_matching.NearestNeighborDistanceMetric(
    "cosine", matching_threshold=0.2, budget=100)
tracker = Tracker(metric)

# Run tracker on first part of the sequence.
# [...]

# Save tracker state.
with open("/tmp/tracker_state.pkl", "wb") as f:
    pickle.dump(tracker, f)

# Restore tracker state.
with open("/tmp/tracker_state.pkl", "rb") as f:
    tracker = pickle.load(f)

# Run tracker on second part of the seqeuence.
#[...]
```

Again, this code snippet will currently fail, but the fix is straight-forward. I will push a fix as soon as I find the time.

**Comment by nwojke** [comment]
The fix is in and the code snippet above should work now. I close this, but feel free to re-open if this didn't solve your problem.
