### ISSUE TITLE
gate_cost_matrix output

### ISSUE THREAD

**Issue by arun-kumark** [nwojke/deep_sort#84]
Dear all,

I could be really silly in doing this, but I am very new to this code.

I was trying to figure out the the gate_cost_matrix output, please help me understanding the output and do correct my understanding.
Inside the _match function in tracker.py file, I wanted to understand the cost_matrix output, so I placed two logs, before and after the output of the gate_cost_matrix function.

Here is the output; -

**Cost Matrix - Before** 
 [[0.10091007 0.07897657]
 [0.01140398 0.2716397 ]]

**Cost Matrix -After** 
 [[1.00000000e+05 7.89765716e-02]
 [1.14039779e-02 1.00000000e+05]]

Now I checked there is a INF values coming in the gate_cost_matrix output so I commented the cost_matrix and put the threshold to INF in nn_matching.py file.

After this change the output of the videos get much better (Means, till the person is in the vicinity of the camera, it works perfectly, even it remembers the person if it reappears, but it swaps the ID's if two people if they appears or disappears at same time) means, the problem is still with the re-identification.

Can you help me understanding the Above outputs. And What other changes can I make to make the detection consistent.

**Comment by arun-kumark** [comment]
In addition to the above question, 
I want to separate the (Tracks, Detections) extraction and want to dump in a file, which I can use later offline, to detect the people by IDs in the other videos using the dump. Is it possible in the current framework, can you help me, what will make it difficult/infeasible?

**Comment by Phoebe-star** [comment]
how do you print the value?

**Comment by nwojke** [comment]
[The function](https://github.com/nwojke/deep_sort/blob/master/deep_sort/linear_assignment.py#L144) replaces the cost of all invalid assignments with a constant. An assignment can be invalid because the appearance feature distance is larger than a threshold or because the measurement is outside of the gate, i.e., the region where the track is expected with a certain confidence based on Kalman filtering.

This is done because we don't want a notion of *more or less* invalid in the assignment problem; each invalid assignment should be weighted equally.

What I found interesting is that the cost is set to _INF, or ``1e+05``. This is a bug and should be changed to ``threshold + EPSILON`` where threshold is the gating threshold and ``EPSILON`` is a small number.

With respect to your investigation, I am not sure if I understand you correctly. If you have changed the the threshold of the appearance feature to _INF but you still get ID swaps then it could be the motion component which is causing the swap. You might want to add [this line](https://github.com/nwojke/deep_sort/blob/master/application_util/visualization.py#L132) to visualize the Kalman filter gate of the position.

**Comment by arun-kumark** [comment]
thank you for the comment Nicolai.
I will prepare the video with my code changes and will share for your observation, may be the end of this week.

**Comment by ss199302** [comment]
@nwojke   As you say"What I found interesting is that the cost is set to _INF, or 1e+05. I'd say this is a bug and should be changed to threshold + EPSILON where threshold is the gating threshold and EPSILON is a small number" but i find  you did't change it in you code? so what's  the value of gated_cost

**Comment by meloncolie** [comment]
@nwojke Should I disable the function gate_cost_matrix, if a weak detector and a deep feature exactor (e.g. feature of face recognition deep model) are used. In this case, the feature exactor is more reliable; face can be frequently not be detected, and motion of bboxes can not fulfill Kalman filtering.
